### ISSUE TITLE
Add CONTRIBUTION.md

### ISSUE THREAD

**Issue by mindninjaX** [Basecamp-Community/React-Pomodoro-Timer-BuildWithMe#2]
This project is Open Source so having a decent Contribution guide will be great. No specific requirements, just a basic CONTRIBUTION.md 📃

**Comment by danger-ahead** [comment]
Please consider assigning me. I can do that!

**Comment by mindninjaX** [comment]
Hi @danger-ahead! Thanks a lot for your interest in contributing ⭐ 
I've assigned this issue to you, please go ahead ⚡

**Comment by danger-ahead** [comment]
@mindninjaX kindly have a look!

**Comment by mindninjaX** [comment]
Hey @danger-ahead! I have requested a small change in **CONTRIBUTION.md** in your PR.

This shouldn't take more than 2 minutes. Please go ahead and commit the change. 😊
